name: gerarddeane
favicon: null
layout_spectrum: 0.9789161263033748
typography_spectrum: 0.8627953883260489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.42653334443457425
  lightness: 0.5539974111597985
  saturation: 0.4776406269520521
  rhythmicContrast: 0.8324101292528212
purpose: []
